/******************************************************************************/
/***          Generated by IBExpert 2012.02.21 20/03/2026 14:58:03          ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES NONE;

CREATE DATABASE '127.0.0.1:D:\Sistema de Horas Delphi\Base dados\Base_Dados_Horas.gdb'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET NONE COLLATION NONE;



/******************************************************************************/
/***                               Generators                               ***/
/******************************************************************************/

CREATE GENERATOR GEN_ATIVIDADES;
SET GENERATOR GEN_ATIVIDADES TO 52;

CREATE GENERATOR GEN_CORPO;
SET GENERATOR GEN_CORPO TO 297;

CREATE GENERATOR GEN_ITENS_RECEITA;
SET GENERATOR GEN_ITENS_RECEITA TO 64;

CREATE GENERATOR GEN_MOVIMENTACAO_HORA;
SET GENERATOR GEN_MOVIMENTACAO_HORA TO 14247;

CREATE GENERATOR GEN_RECEITAS;
SET GENERATOR GEN_RECEITAS TO 5;

CREATE GENERATOR GEN_TAREFAS;
SET GENERATOR GEN_TAREFAS TO 49;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE CAD_ATIVIDADES (
    ATI_CODIGO     INTEGER NOT NULL,
    ATI_DESCRICAO  VARCHAR(100),
    ATI_OBS        VARCHAR(200),
    ATI_TIPO       CHAR(1)
);

CREATE TABLE CORPO (
    ID_CORPO  INTEGER NOT NULL,
    DATA      TIMESTAMP,
    PESO      NUMERIC(8,3),
    CINTURA   INTEGER,
    OBS       VARCHAR(250)
);

CREATE TABLE ITENS_RECEITA (
    ID           INTEGER NOT NULL,
    INGREDIENTE  VARCHAR(200),
    ID_RECEITA   INTEGER NOT NULL
);

CREATE TABLE MOVIMENTACAO_HORA (
    ID_MOVIMENTACAO_HORA  INTEGER NOT NULL,
    DATA                  TIMESTAMP,
    ATI_CODIGO            INTEGER NOT NULL,
    OBS                   VARCHAR(200),
    QTDE_HORAS            TIME,
    ACORDAR               TIME
);

CREATE TABLE RECEITAS (
    ID              INTEGER NOT NULL,
    TITULO_RECEITA  VARCHAR(120),
    MODO_PREPARO    VARCHAR(4000)
);

CREATE TABLE TAREFAS (
    ID_TAREFA        INTEGER NOT NULL,
    DATA             TIMESTAMP,
    OBS              VARCHAR(250),
    DATA_FINALIZADO  TIMESTAMP,
    OPCAO            CHAR(1)
);



/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE CAD_ATIVIDADES ADD PRIMARY KEY (ATI_CODIGO);
ALTER TABLE ITENS_RECEITA ADD PRIMARY KEY (ID);
ALTER TABLE MOVIMENTACAO_HORA ADD PRIMARY KEY (ID_MOVIMENTACAO_HORA);
ALTER TABLE RECEITAS ADD PRIMARY KEY (ID);


/******************************************************************************/
/***                              Foreign Keys                              ***/
/******************************************************************************/

ALTER TABLE ITENS_RECEITA ADD FOREIGN KEY (ID_RECEITA) REFERENCES RECEITAS (ID);
ALTER TABLE MOVIMENTACAO_HORA ADD FOREIGN KEY (ATI_CODIGO) REFERENCES CAD_ATIVIDADES (ATI_CODIGO);


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/


SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: CODIGO_ATIVIDADE */
CREATE TRIGGER CODIGO_ATIVIDADE FOR CAD_ATIVIDADES
ACTIVE BEFORE INSERT POSITION 0
as
 begin
  new.ati_codigo = gen_id(gen_atividades,1);
 end
^

/* Trigger: CODIGO_CORPO */
CREATE TRIGGER CODIGO_CORPO FOR CORPO
ACTIVE BEFORE INSERT POSITION 0
as
 begin
  new.id_corpo = gen_id(gen_corpo,1);
 end
^

/* Trigger: CODIGO_ITENS_RECEITA */
CREATE TRIGGER CODIGO_ITENS_RECEITA FOR ITENS_RECEITA
ACTIVE BEFORE INSERT POSITION 0
as
 begin
  new.id = gen_id(GEN_ITENS_RECEITA,1);
 end
^

/* Trigger: CODIGO_MOVIMENTACAO_HORA */
CREATE TRIGGER CODIGO_MOVIMENTACAO_HORA FOR MOVIMENTACAO_HORA
ACTIVE BEFORE INSERT POSITION 0
as
 begin
  new.id_movimentacao_hora = gen_id(gen_movimentacao_hora,1);
 end
^

/* Trigger: CODIGO_RECEITAS */
CREATE TRIGGER CODIGO_RECEITAS FOR RECEITAS
ACTIVE BEFORE INSERT POSITION 0
as
 begin
  new.id = gen_id(gen_receitas,1);
 end
^

/* Trigger: CODIGO_TAREFAS */
CREATE TRIGGER CODIGO_TAREFAS FOR TAREFAS
ACTIVE BEFORE INSERT POSITION 0
as
 begin
  new.id_tarefa = gen_id(gen_tarefas,1);
 end
^

SET TERM ; ^

